---
language: node_js
node_js: "10"
dist: xenial

addons:
  chrome: stable

cache: yarn

env:
  global:
    - JOBS=1

branches:
  only:
    - master
    - /^release/\d+\.\d+/

jobs:
  include:
    - stage: "Tests"
      before_install:
        - npm install -g codecov
        - npm install -g @commitlint/travis-cli
        - yarn --version
      script:
        - commitlint-travis
        - yarn lint
        - yarn test
      after_success:
        - npm run codecov

    - stage: "Release"
      script: skip
      before_install:
        - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git fetch pub master
        - git checkout -qf ${TRAVIS_BRANCH}
      deploy:
        - provider: script
          skip_cleanup: true
          script: npm run release -- --yes --git-remote pub
        - provider: script
          skip_cleanup: true
          script: npx lerna publish from-package --yes

stages:
  - "Tests"
  - name: "Release"
    if: branch = master
