---
language: node_js
node_js: stable
sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm

env:
  global:
    - JOBS=1

jobs:
  fail_fast: true

  include:
    - stage: "Tests"
      before_install:
        - npm config set spin false
        - npm install -g npm@6
        - npm install -g codecov
        - npm install -g greenkeeper-lockfile@1
        - npm install -g @commitlint/travis-cli
        - npm --version
      install:
        - if [[ $TRAVIS_BRANCH =~ greenkeeper || $TRAVIS_PULL_REQUEST_BRANCH =~ greenkeeper ]]; then npx lerna bootstrap --no-ci; else npx lerna bootstrap --ci; fi
      before_script:
        - greenkeeper-lockfile-update
      script:
        - commitlint-travis
        - npm run lint
        - npm test
      after_script:
        - greenkeeper-lockfile-upload
      after_success:
        - npm run codecov

    - stage: "Release"
      script: skip
      before_install:
        - git remote add pub https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git
        - git checkout -qf ${TRAVIS_BRANCH}
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npm run release -- --yes --git-remote pub

stages:
  - "Tests"
  - name: "Release"
    if: branch = master

