---
language: node_js
node_js:
  - "stable"

sudo: false
dist: trusty

before_install:
  - npm config set spin false
  - npm install -g npm@^5.7
  - npm --version
  - cd eslint-plugin-bbva

install:
  - npm ci

script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - npm run lint
  - npm run test
